import src1 from '../images/cars/1-VW-Tiguan-2019.png';
import src2 from '../images/cars/2-Highlander-2014.png';
import src3 from '../images/cars/3-Luxus-Lucxury-2017.png';
import src4 from '../images/cars/4-Highlander-2016.png';
import src5 from '../images/cars/5-Elantra-2017.png';
import src6 from '../images/cars/6-MB-GLE-2016.png';
import src7 from '../images/cars/7-Toyota-Venza-2015.png';
import src8 from '../images/cars/8-Lexus-F-Sport-2016.png';
import src9 from '../images/cars/1-VW-Tiguan-2019.png';
import src10 from '../images/cars/2-Highlander-2014.png';
import src11 from '../images/cars/3-Luxus-Lucxury-2017.png';
import src12 from '../images/cars/4-Highlander-2016.png';
import src13 from '../images/cars/7-Toyota-Venza-2015.png';
import src14 from '../images/cars/8-Lexus-F-Sport-2016.png';
import src15 from '../images/cars/12-Toyota-Venza-2015.png';
import src16 from '../images/cars/2-Highlander-2014.png';
import src17 from '../images/cars/3-Luxus-Lucxury-2017.png';
import src18 from '../images/cars/4-Highlander-2016.png';

const cars = [
  {
    id: 1,
    source: src1,
    year: 2016,
    model: 'Volkswagen Tiguan',
    mileAge: '19,855',
    transmission: 'Automatic',
    engineType: 'Diesel',
    price: '34,888',
    isSold: false,
    isNew: false,
  },
  {
    id: 2,
    source: src2,
    year: 2014,
    model: 'Toyota Hightlander XLE',
    mileAge: '69,000',
    transmission: 'Automatic',
    engineType: 'Gas',
    price: '27,875',
    isSold: false,
    isNew: true,
  },
  {
    id: 3,
    source: src3,
    year: 2017,
    model: 'Lexus RX 350 LUXURY',
    mileAge: '39,850',
    transmission: 'Automatic',
    engineType: 'Gas',
    price: '27,875',
    isSold: false,
    isNew: false,
  },
  {
    id: 4,
    source: src4,
    year: 2016,
    model: 'Toyota Highlander LE A...',
    mileAge: '104,000',
    transmission: 'Automatic',
    engineType: 'Gas',
    price: '23,728',
    isSold: false,
    isNew: false,
  },
  {
    id: 5,
    source: src5,
    year: 2017,
    model: 'Hyundai Elantra',
    mileAge: '95,000',
    transmission: 'Automatic',
    engineType: 'Gas',
    price: '11,788',
    isSold: false,
    isNew: false,
  },
  {
    id: 6,
    source: src6,
    year: 2016,
    model: 'Mercedes-Benz GLE-Cl...',
    mileAge: '59,80',
    transmission: 'Automatic',
    engineType: 'Diesel',
    price: '38,878',
    isSold: false,
    isNew: false,
  },
  {
    id: 7,
    source: src7,
    year: 2015,
    model: 'Toyota Venza AWD XLE...',
    mileAge: '99,000',
    transmission: 'Automatic',
    engineType: 'Gas',
    price: '18,620',
    isSold: true,
    isNew: false,
  },
  {
    id: 8,
    source: src8,
    year: 2016,
    model: 'Lexus RX 350 F-SPORT',
    mileAge: '86,000',
    transmission: 'Automatic',
    engineType: 'Gas',
    price: '34,88',
    isSold: false,
    isNew: true,
  },
  {
    id: 9,
    source: src9,
    year: 2016,
    model: 'Volkswagen Tiguan',
    mileAge: '19,855',
    transmission: 'Automatic',
    engineType: 'Diesel',
    price: '34,888',
    isSold: false,
    isNew: false,
  },
  {
    id: 10,
    source: src10,
    year: 2014,
    model: 'Toyota Hightlander XLE',
    mileAge: '69,000',
    transmission: 'Automatic',
    engineType: 'Gas',
    price: '27,875',
    isSold: true,
    isNew: false,
  },
  {
    id: 11,
    source: src11,
    year: 2017,
    model: 'Lexus RX 350 LUXURY',
    mileAge: '39,850',
    transmission: 'Automatic',
    engineType: 'Gas',
    price: '27,875',
    isSold: false,
    isNew: false,
  },
  {
    id: 12,
    source: src12,
    year: 2016,
    model: 'Toyota Highlander LE A...',
    mileAge: '104,000',
    transmission: 'Automatic',
    engineType: 'Gas',
    price: '23,728',
    isSold: false,
    isNew: false,
  },
  {
    id: 13,
    source: src13,
    year: 2015,
    model: 'Toyota Venza AWD XLE...',
    mileAge: '99,000',
    transmission: 'Automatic',
    engineType: 'Gas',
    price: '18,620',
    isSold: true,
    isNew: false,
  },
  {
    id: 14,
    source: src14,
    year: 2016,
    model: 'Lexus RX 350 F-SPORT',
    mileAge: '86,000',
    transmission: 'Automatic',
    engineType: 'Gas',
    price: '34,88',
    isSold: false,
    isNew: true,
  },
  {
    id: 15,
    source: src15,
    year: 2016,
    model: 'Volkswagen Tiguan',
    mileAge: '19,855',
    transmission: 'Automatic',
    engineType: 'Diesel',
    price: '34,888',
    isSold: false,
    isNew: true,
  },
  {
    id: 16,
    source: src16,
    year: 2014,
    model: 'Toyota Hightlander XLE',
    mileAge: '69,000',
    transmission: 'Automatic',
    engineType: 'Gas',
    price: '27,875',
    isSold: true,
    isNew: false,
  },
  {
    id: 17,
    source: src17,
    year: 2017,
    model: 'Lexus RX 350 LUXURY',
    mileAge: '39,850',
    transmission: 'Automatic',
    engineType: 'Gas',
    price: '27,875',
    isSold: false,
    isNew: false,
  },
  {
    id: 18,
    source: src18,
    year: 2016,
    model: 'Toyota Highlander LE A...',
    mileAge: '104,000',
    transmission: 'Automatic',
    engineType: 'Gas',
    price: '23,728',
    isSold: false,
    isNew: false,
  },
]

export default cars;
